name: Package Locales

on:
  push:

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        locale:
          - cs
          - de
          - fr
          - nl
          - sl
          - tr

    steps:
      - name: Check out repository
        uses: actions/checkout@v4
      
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install DSW Locale Packager
        run: |
          npm install @ds-wizard/locale-packager@0.2.0

      - name: Create locale package (unzipped)
        run: |
          mkdir out
          npx dsw-locale-packager locales/${{ matrix.locale }} -o out/

      - name: Upload packages as artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.locale }}-locale
          path: out/

  update:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        locale:
          - cs
          - de
          - fr
          - nl
          - sl
          - tr

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          node-version: '3.12'

      - name: Install dependencies
        run: |
          npm install @ds-wizard/locale-packager@0.2.0
          pip install -r scripts/requirements.txt

      - name: Create locale package (ZIP)
        run: |
          mkdir out
          npx dsw-locale-packager locales/${{ matrix.locale }} -o out/locale.zip -z

      - name: Push to DSW
        run: |
          python scripts/dsw-locales.py clear -y -o dsw -l ${{ matrix.locale }}
          python scripts/dsw-locales.py push out/locale.zip -e
        env:
          DSW_API_URL: ${{ secrets.TRANSLATORS_DSW_API_URL }}
          DSW_API_KEY: ${{ secrets.TRANSLATORS_DSW_API_KEY }}
