name: Release Locale

on:
  push:
    tags:
      - v*


jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Extract tag
        run: |
          echo "TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      
      - name: Extract version
        run: |
          VERSION=$(echo $TAG | sed 's/^v\([0-9]*\.[0-9]*\.[0-9]*\)-.*$/\1/')
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      
      - name: Extract language code
        run: |
          LANG=$(echo $TAG | sed 's/^v[0-9]*\.[0-9]*\.[0-9]*-\(.*\)$/\1/')
          echo "LANG=${LANG}" >> $GITHUB_ENV
      
      - name: Check locale to release
        run: |
          ls -lah locales/$LANG

      - name: Install DSW Locale Packager
        run: |
          npm install @ds-wizard/locale-packager@0.2.0

      - name: Create locale ZIP package
        run: |
          mkdir out
          npx dsw-locale-packager locales/$LANG -o out/locale.zip -z
          
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: ${{ github.ref }}
          tag_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Upload ZIP package to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./out/locale.zip
          asset_name: dsw_${{ env.LANG }}_${{ env.VERSION }}.zip
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ github.token }}
